Debug information for file: javali_tests/HW2/OkSimpleReturn.javali
AST Resulting From Parsing Stage:
ClassDecl (name: Main, superClass: Object)
| MethodDecl (argumentNames: [], argumentTypes: [], name: m, returnType: int)
| | Seq ()
| | Seq ()
| | | ReturnStmt ()
| | | | IntConst (value: 0)
| MethodDecl (argumentNames: [], argumentTypes: [], name: main, returnType: void)
| | Seq ()
| | | VarDecl (name: res, type: int)
| | Seq ()
| | | Assign ()
| | | | Var (name: res)
| | | | UnaryOp (operator: U_MINUS)
| | | | | IntConst (value: 1)
| | | Assign ()
| | | | Var (name: res)
| | | | MethodCallExpr (methodName: m)
| | | | | ThisRef ()
| | | BuiltInWrite ()
| | | | Var (name: res)
| | | BuiltInWriteln ()
| | | Assign ()
| | | | Var (name: res)
| | | | MethodCallExpr (methodName: m)
| | | | | ThisRef ()
| | | BuiltInWrite ()
| | | | Var (name: res)
| | | BuiltInWriteln ()

Test failed because an exception was thrown:
    null
Stack trace:
cd.ToDoException
	at cd.frontend.semantic.SemanticAnalyzer.check(SemanticAnalyzer.java:20)
	at cd.Main.semanticCheck(Main.java:111)
	at cd.test.AbstractTestAgainstFrozenReference.testSemanticAnalyzer(AbstractTestAgainstFrozenReference.java:145)
	at cd.test.AbstractTestAgainstFrozenReference.test(AbstractTestAgainstFrozenReference.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
